### ISSUE TITLE
Armor rating and inventory bug

### ISSUE THREAD

**Issue by BHasselaar** [AzumattDev/OdinsQOL#1]
I tried to use this mod, but I keep encountering this bug where my character gets 1090 armor and loses one row of inventory slots. Expanded inventory in mod options is off and I excluded other mods that messed with inventory or armor.

**Comment by AzumattDev** [comment]
Please let me know your mod list, armor you are wearing, and the situations in which it happens.

For best results, provide me with your character file, mod list, BepInEx/LogOutput.log files, and the OdinQOL config file. Thanks!

**Comment by BHasselaar** [comment]
> Please let me know your mod list, armor you are wearing, and the situations in which it happens.

 I installed DoOrDieSoloExperience and all its dependencies from the thunderstore using r2modman installer, then your mod because it was recommended in the documentation.
 It happened while opening the game, and it didn't matter the armor or item in the inventory, the armor number was always 1090
  
> For best results, provide me with your character file, mod list, BepInEx/LogOutput.log files, and the OdinQOL config file. Thanks!

All the characters I created and already had appeared with the bug

my modlist is the following, all with default configuration:
denikson-BepInExPack_Valheim-5.4.1901
HugotheDwarf-Shapekeys_and_More-1.1.0
HugotheDwarf-More_and_Modified_Player_Cloth_Colliders-3.0.1
ValheimModding-Jotunn-2.7.3
RandyKnapp-ExtendedItemDataFramework-1.0.7
Advize-PlantEverything-1.11.5
LambaSun-EpicMMOSystem-1.2.8
Frenvius-Valharvest-2.0.1
KGvalheim-MagicOverhaul-1.5.594
OdinPlus-KnarrTheTrader-0.2.6
OdinPlus-PotionPlus-4.1.1
RockerKitten-BoneAppetit-3.2.0
OdinPlus-Digitalroot_Valheim_SlopeCombatFix-2.0.0
Smoothbrain-Evasion-1.0.0
Smoothbrain-Starvation-1.0.0
Smoothbrain-DualWield-1.0.2
Smoothbrain-Mining-1.1.1
Smoothbrain-Tenacity-1.0.0
Smoothbrain-Cooking-1.1.3
Smoothbrain-Vitality-1.0.0
Smoothbrain-Blacksmithing-1.1.2
Smoothbrain-PassivePowers-1.0.3
Smoothbrain-SteadyRegeneration-1.0.0
Smoothbrain-CreatureLevelAndLootControl-4.4.9
Smoothbrain-Jewelcrafting-1.1.12
Azumatt-WardIsLove-2.3.9
HugotheDwarf-Hugos_Armory-7.1.0
GoldenJude-Blacksmiths_tools-2.0.2
GoldenJude-Judes_Equipment-2.2.0
ASharpPen-This_Goes_Here-2.1.1
ASharpPen-Drop_That-2.3.3
ASharpPen-Spawn_That-1.0.5
MonsterLabZ-MonsterLabZ-2.4.4
Horem-Fruit_Trees-0.1.1
Horem-Deds_Army-0.1.2
Horem-Minotaurs-0.2.0
Horem-Supply_Crates-0.0.9
Horem-Farmyard_Animals-0.2.0
Horem-Fancy_Foods-0.0.3
Horem-Fantasy_Creatures-0.2.2
Horem-Fee_Fi_Fo_Fum-0.1.2
Horem-Fantasy_Armoury-0.0.8
Horem-Do_or_Die_Items-0.1.4
Horem-Instanced_Villages-0.0.4
Horem-Do_Or_Die_NPC-0.2.1
Horem-Wildlife-0.0.2
Horem-Do_Or_Die_Biomes-0.1.1
Horem-LessFoodDegradation-1.1.1
Horem-DoOrDieMonsters-0.6.1
Horem-DoOrDieSoloExperience-2.0.6
OdinPlus-OdinsQOL-0.8.2

**Comment by AzumattDev** [comment]
Have you tried with Just OdinsQOL to see if you get the issue?

If only OdinsQOL is installed and the issue persists...then that is something that I can look into. Though, to me, it sounds like you downloaded a mod pack without knowing much of what it does. DoOrDie is extensive and has a lot of configurations.

The armor issue would be coming from a mod (maybe Jewelcrafting or EpicMMO) that gives bonuses to your armor rating for various reasons.

**Comment by AzumattDev** [comment]
Hey there!

So I downloaded OdinQOL and the DoOrDie SoloExperience and still do not have this issue. I am happy to share my profile with you in r2modman if you wish. I am deeming this not a bug on this mod's part and possibly something else you have.

Here is a video showing my experience: [https://youtu.be/ZKormknB1j4](https://youtu.be/ZKormknB1j4)
