### ISSUE TITLE
Food buffs don't decay

### ISSUE THREAD

**Issue by creativegaffers** [AzumattDev/OdinsQOL#15]
This changes the vanilla behavior where buffs decay gradually over time, and there does not appear to be any configuration option to disable this.  No mention in the docs about the mod enabling this behavior.

**Comment by AzumattDev** [comment]
Yes, I do apologize. The mod was originally made for an old server that died out. Some of the code is residual and I have not even viewed it all yet. I am slowly making everything configurable. I will do my best effort to overhaul the mod soon with more configuration options.

**Comment by creativegaffers** [comment]
No problem, I figured this was just the easiest place for you to keep track of it, if it was something you cared about.

**Comment by AzumattDev** [comment]
Definitely the easiest place. Thank you for posting it here.
