### ISSUE TITLE
unknown error in console

### ISSUE THREAD

**Issue by steve541** [AzumattDev/OdinsQOL#16]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
OdinQOL.Patches.MapDetail+<UpdateMap>d__12.MoveNext () (at <b3642ea41c23472191c51c94ec3a4cca>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <c9fb31c2eee14ce4aeb36e4c61e154d8>:0)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
OdinQOL.OdinQOLplugin:Update()

**Comment by AzumattDev** [comment]
This error has already been fixed in the current code. For now, you have to make sure "Show Buildings" and "MapDetails" are both set to the same value.
