### ISSUE TITLE
Inventory completely broken

### ISSUE THREAD

**Issue by RedDust99** [AzumattDev/OdinsQOL#17]
Hello,

I had valheim plus before with the patches it stopped working as you know.  I did a complete reinstall of the game removing everything.   Did a fresh install of BepinEx and added your mod through Thunderstore.  I'm gathering since everything was crated with Valheim Plus that I'll continue to randomly run into problems?  Currently I opened a chest to re-stack things, took everything into inventory and ended up with all my empty bag slots stuck with a yellow background icon that looks like withered bone icon, no portal icon and fork in the upper right hand corner.  It says 1/3 with a white bar at the bottom and says Tooltip when you hover over the icon.  I cannot move anything out of my inventory to put back in the box, nor drop it.  As well it completely trashes the workbench.  Thanks otherwise things were going fine.

**Comment by assBuk** [comment]
@RedDust99 Valheim Plus does not work with OdinQOL and never has

---

Now some modifications do not support V+
I recommend switching to OdinQOL instead of V+.

---

If your hosting does not allow you to give up V+
I advise you to use the VMinus mod.
Or change your hosting

**Comment by AzumattDev** [comment]
@RedDust99 Sounds to me like you used V+ to give you more slots and such, but didn't mimic that inside of OdinQOL. You need to make sure that you have the same number of rows and columns as you did in V+ for your inventory.

This is a configuration problem, not an issue with the mod. I will be closing this issue. Feel free to join one of the discords below if you are still having issues.


### My Discord:
https://discord.gg/pdHgy6Bsng

### OdinPlus Discord:
https://discord.gg/Pb6bVMnFb2

**Comment by RedDust99** [comment]
Thank you for your response.  I figured it was a mismatch and the fault was on my end.  Thanks again.

**Comment by Roxxapo** [comment]
I've encountered this issue while never having installed valheim+ and being on a new character.
What does it for me is when a container has more than 6 rows and you press the take all key the character inventory becomes corrupted and the only option is to load a character backup or start a new character.
