### ISSUE TITLE
Could not load [OdinPlusQOL 0.9.2] because it is incompatible with: org.bepinex.plugins.valheim_plus

### ISSUE THREAD

**Issue by Mar-Veloz** [AzumattDev/OdinsQOL#18]
Apparently, with the compatibility checks re-introduced in latest update, the mod considers itself incompatible with V+. This is a surprise to me, as I have been using both together without trouble for months now.

Is there any list of which mods OdinQOL is incompatible with and why?

**Comment by AzumattDev** [comment]
OdinsQOL is incompatible with V+ and always had been. I just finally added the incompatibility. The fact you were using them side-by-side for awhile is a bit scary that you didn't notice the issues that are present when doing so.

It is not compatible with any mod of Aedenthorn's that performs the same functions as OdinQOL has those integrated, fixed, and performant in it.

**Comment by Mar-Veloz** [comment]
@AzumattDev Obviously it will cause problems if you try to activate the same function in both, but there are functions in V+ that are not in OdinsQOL (such as Advanced Building Mode), and activating those (and only those) should not (and as far as I can tell, does not) cause any problems.

Is there/would it be possible to add some sort of "I know what I'm doing" button/config to bypass this check?

**Comment by AzumattDev** [comment]
There is not. There are issues even if "You know what you're doing"

Again, I am very surprised they have been working for you. There should have been many issues and bugs that you'd experience just having them both installed.

And before you ask, I do not plan on removing the incompatibility. It was meant to be there from the start.

**Comment by Mar-Veloz** [comment]
@AzumattDev I see. In that case, would you be willing to make the Auto Store feature available as a standalone mod, similarly to how the CFC and player inventory features are available as standalone mods?

**Comment by AzumattDev** [comment]
I will do that for you soon, yes. It's on my list to re-work OdinQOL entirely.

**Comment by Mar-Veloz** [comment]
Great, thanks so much!
