### ISSUE TITLE
Workbench range indicator disappears when 'Change No Roof Behavior' is set to true

### ISSUE THREAD

**Issue by Mar-Veloz** [AzumattDev/OdinsQOL#2]
When the `Change No Roof Behavior` setting in the `Workbench` section is set to true, the dotted line that indicates the range of a workbench when using the hammer stops being visible. This is especially problematic because the setting is set to true by default.

Example of the range indicator I'm talking about:
![Valheim 2022-07-23 23_49_46](https://user-images.githubusercontent.com/45543932/180631346-2d2fa51d-e70e-409b-8c53-2a5fa785db0c.png)

**Comment by AzumattDev** [comment]
Looking into it.

**Comment by Lime18** [comment]
Looks like this change broke this feature
![image](https://user-images.githubusercontent.com/29817277/180651181-1a9a1823-e85d-481c-9a71-b4379be41969.png)
![image](https://user-images.githubusercontent.com/29817277/180651186-edda12c7-471e-4b58-9e17-fb7b93a56510.png)

**Comment by Lime18** [comment]
my problem, didn't enable the `Allow Workbench Alterations` xD
