### ISSUE TITLE
BepInEx Error - JADS Mistlands Modpack

### ISSUE THREAD

**Issue by GaelenOfLore** [AzumattDev/OdinsQOL#20]
[error  :   BepInEx] Could not load [BuildPieces 1.1.0] because it is incompatible with: org.bepinex.plugins.valheim_plus
[error  :   BepInEx] Could not load [PortalPlane 1.0.6] because it is incompatible with: org.bepinex.plugins.valheim_plus
[error  :   BepInEx] Could not load [OdinPlusQOL 0.9.5] because it is incompatible with: org.bepinex.plugins.valheim_plus

Game boots, creates a new character and seed, loads in fine, all seems to work, I can pick things up BUT there is nothing in the crafting menu. No recipes unlocked when I picked up rocks and branches.
Disabled these three, (they disable JADS_Mistlands_Modpack but nothing else) as well as PlanBuild and.... still no recipes.

Thoughts? Go through the modpack installing them one at a time perhaps?

**Comment by AzumattDev** [comment]
My thoughts are, to read the errors.
