### ISSUE TITLE
AutoStorage hotkey doesn't work with 'Build It' mod

### ISSUE THREAD

**Issue by paul-cpp** [AzumattDev/OdinsQOL#22]

**Comment by paul-cpp** [comment]
Hi! AutoStore hotkey and autopickup from the ground doesn't work for 'Build It' mod containters. But 'Deposit items' button works.
Reproduced on small and big crates

**Comment by AzumattDev** [comment]
This is a known issue with her containers. OdinsQOL is currently being split out into modular mods and will soon go away as a "big mod"

AzuAutoStore is the replacement for this specific feature and that problem doesn't exist.

**Comment by paul-cpp** [comment]
Found log, maybe this is related to the problem:

`
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
OdinQOL.Patches.AutoStorePatch.DisallowItem (Container container, ItemDrop+ItemData item) (at <74803bbf05b04d9bbed55a7ec73b9e16>:0)
OdinQOL.Patches.AutoStorePatch.TryStoreItem (Container __instance, ItemDrop+ItemData& item) (at <74803bbf05b04d9bbed55a7ec73b9e16>:0)
OdinQOL.Patches.AutoStorePatch+Container_CheckForChanges_Patch.Postfix (Container __instance, ZNetView ___m_nview) (at <74803bbf05b04d9bbed55a7ec73b9e16>:0)
(wrapper dynamic-method) Container.DMD<Container::CheckForChanges>(Container)
`

**Comment by paul-cpp** [comment]
Thanks!
