### ISSUE TITLE
Jotun Puffs/Magecap Cannot Place w/ PreventPlantTooClose Enabled

### ISSUE THREAD

**Issue by ArsenikMilk** [AzumattDev/OdinsQOL#24]
When the setting PreventPlantTooClose is enabled, I am unable to plant Jotun Puffs or Magecaps. This is regardless of whether the setting IgnoreBiome or PlantAnywhere is enabled or not, so it doesn't work even in Mistlands on cultivated soil. The game provides no error, even when the mushroom is able to be planted; it just doesn't plant when I try to.
Disabling the setting temporarily allows me to plant the crops with no issues (aside from the fact I can plant them too close together), and the setting can be re-enabled afterwards with no issues. This error seems to only apply to the new crops.

**Comment by AzumattDev** [comment]
Known issue
