### ISSUE TITLE
chests inacessible, all slots have a white jewel icon on them, load list as follows

### ISSUE THREAD

**Issue by ThalassicRaysOfTheAphoticSunset** [AzumattDev/OdinsQOL#27]
[LogOutput.log](https://github.com/AzumattDev/OdinsQOL/files/10300317/LogOutput.log)

**Comment by AzumattDev** [comment]
Based on the issue #26. Seems BetterArchery is now causing this.

**Comment by ThalassicRaysOfTheAphoticSunset** [comment]
don't think so, sent you the wrong log, I had OdinsQOL installed, removed it and it worked fine

**Comment by AzumattDev** [comment]
Well as was shown in the issue I tagged, BetterArchery's update is the cause of the problems.
