### ISSUE TITLE
Can't plant Jotun puffs or Magecap with OdinsQOL enabled

### ISSUE THREAD

**Issue by Dynamofire8** [AzumattDev/OdinsQOL#30]
Hello, when using a cultivator in the Mistlands I cannot plant Jotun puffs and Magecaps. I have tried in multiple areas of grassland in the Mistlands that I have tiled into cultivated soil. The puffs and caps show in their correct colour when I have them selected with the cultivator equipped but when I click to plant them it does not plant them. I have no issues planting any other crops with OdinsQOL.

**Comment by Swarm133** [comment]
Not just you. i can confirm this too. i ended up needing to use a seed totem mod to plant them.

**Comment by AzumattDev** [comment]
@Dynamofire8 @Swarm133 

Please see issue #23 and issue #24

**Comment by Dynamofire8** [comment]
Thank you

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Swarm133** [comment]
Thank you
