### ISSUE TITLE
[CFC] Fix crafting with single items (no stack)

### ISSUE THREAD

**Issue by Lime18** [AzumattDev/OdinsQOL#6]
Example on Soulcatcher_KG_JC_Additions mod
![f1](https://user-images.githubusercontent.com/29817277/180634709-dfde8908-eee8-413f-aaab-11e4f2ecdd68.png)
![f2](https://user-images.githubusercontent.com/29817277/180634705-3192ffbd-5ccb-440b-beb5-3dd2f8597883.png)
![f3](https://user-images.githubusercontent.com/29817277/180634703-1bf678e2-24fc-4fa9-8d9a-45f025e89d7c.png)

**Comment by AzumattDev** [comment]
This appears to only be an issue with KG's gems. Pretty sure it's his code or something he forgot is causing it. I cannot get it to happen with anything else.

**Comment by Lime18** [comment]
This can be repeated in vanilla (with items that don't have a stack), here's an example with a club that has had its recipe changed.
There is no such problem when crafting from the inventory.
![image](https://user-images.githubusercontent.com/29817277/180652029-4fd44ba4-f210-4c26-ac90-5fc5d8c40c07.png)
![image](https://user-images.githubusercontent.com/29817277/180652105-17d11fc4-0408-47a6-9f7f-d43a22662c12.png)
![image](https://user-images.githubusercontent.com/29817277/180652116-7fe0d856-c7ea-4783-ad6a-3e11d94db2e0.png)

**Comment by AzumattDev** [comment]
This has been confirmed to be an issue with OdinQOL. Looking into it.
