### ISSUE TITLE
OdinQOL.Patches.ExtendedPlayerInventory Issue

### ISSUE THREAD

**Issue by Sn3akySl0th** [AzumattDev/OdinsQOL#9]
Having issues with OdinsQOL. Get this error when opening the inventory in game.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
OdinQOL.Patches.ExtendedPlayerInventory+InventoryGui_Update_Patch.Postfix (InventoryGui __instance, InventoryGrid ___m_playerGrid, UnityEngine.Animator ___m_animator) (at <82867dc808b9472e9d972a45e5a0e0bf>:0)
(wrapper dynamic-method) InventoryGui.DMD<InventoryGui::Update>(InventoryGui)
[OdinsQOL Issue.txt](https://github.com/AzumattDev/OdinsQOL/files/9391167/OdinsQOL.Issue.txt)

**Comment by AzumattDev** [comment]
The issue is likely caused by these mods that touch the inventory in weird ways.

[BackPacks_Remake 0.3.11]
[HudReplacer 0.0.6]
[InventorySwapper 0.0.7]

[Better Archery 1.7.6] (Make sure the quiver is disabled)

**Comment by AzumattDev** [comment]
Hey there, did you fix your issue by testing the removal of those mods? How's it going?

**Comment by AzumattDev** [comment]
Closing due to no response.
